In [5]:
%ls

 C ����̺��� ����: OS
 ���� �Ϸ� ��ȣ: C269-DEFB

 c:\Users\wjdrb\vscode_code\MathBridge_new\data ���͸�

06/23/2024  06:34 PM    <DIR>          .
06/21/2024  02:18 AM    <DIR>          ..
06/21/2024  01:55 AM         5,649,408 aria2c.exe
06/21/2024  02:47 AM            16,389 arxiv_html_data.ipynb
06/21/2024  02:43 AM             6,807 download_bulk_data.py
06/21/2024  02:06 AM    <DIR>          downloads
06/23/2024  06:34 PM                 0 edit_xml.ipynb
06/21/2024  12:52 AM            21,259 get_arxiv_category.ipynb
06/21/2024  02:51 AM             4,603 get_formula_from_arxiv_html.py
               6�� ����           5,698,466 ����Ʈ
               3�� ���͸�  548,653,305,856 ����Ʈ ����

In [7]:
import xml.etree.ElementTree as ET
import pandas as pd

def parse_xml_to_dataframe(xml_file):
    # XML 파일 파싱
    tree = ET.parse(xml_file)
    root = tree.getroot()
    
    # XML 데이터를 저장할 리스트
    data = []
    
    # XML 파일의 각 요소를 순회하며 데이터 추출
    for child in root:
        row_data = {}
        for element in child:
            row_data[element.tag] = element.text
        data.append(row_data)
    
    # 리스트를 DataFrame으로 변환
    df = pd.DataFrame(data)
    return df

# XML 파일 경로
xml_file_path = r'C:\Users\wjdrb\vscode_code\MathBridge_new\data\downloads\arXiv_src_manifest.xml'

# DataFrame으로 변환
df = parse_xml_to_dataframe(xml_file_path)

In [8]:
df

,content_md5sum,filename,first_item,last_item,md5sum,num_items,seq_num,size,timestamp,yymm
0,cacbfede21d5dfef26f367ec99384546,src/arXiv_src_0001_001.tar,astro-ph0001001,quant-ph0001119,949ae880fbaf4649a485a8d9e07f370b,2364,1,225605507,2010-12-23 00:13:59,0001
1,d90df481661ccdd7e8be883796539743,src/arXiv_src_0002_001.tar,astro-ph0002001,quant-ph0002094,4592ab506cf775afecf4ad560d982a00,2365,1,227036528,2010-12-23 00:18:09,0002
2,3388afd7bfb2dfd9d3f3e6b353357b33,src/arXiv_src_0003_001.tar,astro-ph0003001,quant-ph0003151,b5bf5e52ae8532cdf82b606b42df16ea,2600,1,230986882,2010-12-23 00:22:15,0003
3,46abb309d77065fed44965cc26a4ae2e,src/arXiv_src_0004_001.tar,astro-ph0004001,quant-ph0004109,9bf1b55890dceec9535ef723a2aea16b,2076,1,191559408,2010-12-23 00:26:31,0004
4,ea665c7b62eaac91110fa344f6ba3fc4,src/arXiv_src_0005_001.tar,astro-ph0005001,quant-ph0005134,b49af416746146eca13c5a6a76bc7193,2724,1,255509072,2010-12-23 00:30:11,0005
...,...,...,...,...,...,...,...,...,...,...
8163,1ed0bc87e6b40f64b81295f5652f9938,src/arXiv_src_9909_001.tar,adap-org9909001,solv-int9909028,9d3a7f34f1ac44ad3f495201e24dac90,2500,1,213668821,2010-12-22 23:56:18,9909
8164,4aca046629928ca62367cd65a91a9722,src/arXiv_src_9910_001.tar,adap-org9910001,solv-int9910012,2f3cb5f12de7f8d7051bff7d0efdf2dd,2571,1,244741133,2010-12-23 00:00:30,9910
8165,eba14a08d08e8c356c4d1cdafef68035,src/arXiv_src_9911_001.tar,adap-org9911001,solv-int9911009,af128903c94a5db15b6b5bfbe472ca2f,2517,1,221549097,2010-12-23 00:05:11,9911
8166,3f2743efd4b1351e2b1bada73b0f830d,src/arXiv_src_9912_001.tar,adap-org9912001,solv-int9912016,fb6b0f55935636c4d92445e1f4d47391,2593,1,233445958,2010-12-23 00:09:20,9912
8167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
papaer_2023 = df['yymm'].str.startswith('23', na=False)
papaer_2022 = df['yymm'].str.startswith('22', na=False)
papaer_2021 = df['yymm'].str.startswith('21', na=False)
df_2023 = df[papaer_2023]
df_2022 = df[papaer_2022]
df_2021 = df[papaer_2021]

In [38]:
df_2023
df_2022

,content_md5sum,filename,first_item,last_item,md5sum,num_items,seq_num,size,timestamp,yymm
4422,8387730545e8d96291c209dd2763c337,src/arXiv_src_2201_001.tar,2201.00001,2201.00157,35ca1444ed802dc6e420f88c3e8cf465,157,1,527329435,2023-01-05 07:42:06,2201
4423,782efda5ef119bb2c096c0b6e5acf2ea,src/arXiv_src_2201_002.tar,2201.00158,2201.00382,563f73232975b6f466ea2d6fe2d85b41,225,2,528500173,2024-01-05 08:30:18,2201
4424,80a165e8be0dccdbf5f1ebea9d08f771,src/arXiv_src_2201_003.tar,2201.00383,2201.00531,d36d89fc3965df6d72e0ad66d1cb480f,149,3,553096557,2024-01-05 08:30:44,2201
4425,5d3d3bb0d008e23ef8e27c97650ef47d,src/arXiv_src_2201_004.tar,2201.00532,2201.00722,5888913929fc2be4917f991e3015635c,191,4,589679312,2024-01-05 08:31:12,2201
4426,4cfb8dc8a0c0d8d0a60c1ae7784bec8b,src/arXiv_src_2201_005.tar,2201.00723,2201.00898,fe23a3d66f97e8d41169c1bf6aaa1528,176,5,571992823,2024-01-05 08:31:41,2201
...,...,...,...,...,...,...,...,...,...,...
5697,366c4a8a10798a061c3ff1d2296560b4,src/arXiv_src_2212_101.tar,2212.14156,2212.14301,7c2089a3673af9ab0641b77e4464ffd1,146,101,526339280,2023-01-05 05:00:49,2212
5698,d130d5bc7e41db47936c6172f0ba2e8e,src/arXiv_src_2212_102.tar,2212.14302,2212.14502,116e65e16a7d0328e942e8ec30b96348,201,102,523806532,2023-03-05 06:49:25,2212
5699,e461e42311c401eea7129d06259b9a91,src/arXiv_src_2212_103.tar,2212.14503,2212.14615,0234e991f31f3ba3201b28268b640c34,113,103,542564123,2023-01-05 05:01:39,2212
5700,c2a36fea93bc82f01da94996ae9242e9,src/arXiv_src_2212_104.tar,2212.14616,2212.14751,3018076d329d21f0efb93255c296bd4f,136,104,536501703,2023-12-05 09:11:37,2212
5701,55978aab391aef85ebb039abdc8d9c42,src/arXiv_src_2212_105.tar,2212.14752,2212.14887,8597c7cef22c5389ee0ddd350c6c6d33,136,105,493766926,2023-01-05 05:02:32,2212

In [47]:
total_size = sum(df_2021['size'].astype(int))
# Assuming total_size is the sum of sizes in bytes
total_size_gb = total_size / (1024 ** 3)
total_size_gb

560.3871032735333

In [43]:
import pandas as pd
import xml.etree.ElementTree as ET

def dataframe_to_xml(df, root_tag, row_tag, xml_file_path):
    # XML 루트 요소 생성
    root = ET.Element(root_tag)
    
    # DataFrame의 각 행을 XML 요소로 변환
    for _, row in df.iterrows():
        row_element = ET.SubElement(root, row_tag)
        for col in df.columns:
            cell = ET.SubElement(row_element, col)
            cell.text = str(row[col])
    
    # 트리 구조 생성
    tree = ET.ElementTree(root)
    
    # XML 파일로 저장
    tree.write(xml_file_path, encoding='utf-8', xml_declaration=True)




# DataFrame을 XML 파일로 변환
xml_file_path = 'arXiv_src_manifest_edited.xml'
dataframe_to_xml(df, 'People', 'Person', xml_file_path)

print(f"DataFrame을 {xml_file_path}로 변환했습니다.")

DataFrame을 arXiv_src_manifest_edited.xml로 변환했습니다.